SiliconApp/Models/Breadcrumb.cs
namespace SiliconApp.Models
{
    public class Breadcrumb
    {
        public string Text { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public bool Active { get; set; }

        public Breadcrumb() { }

        public Breadcrumb(string text, string action, string controller, bool active)
        {
            this.Text = text;
            this.Action = action;
            this.Controller = controller;
            this.Active = active;
        }
    }
}

SiliconApp/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;
using SiliconApp.Data;
using SiliconApp.Models;
using SiliconApp.Models.VM;

namespace SiliconApp.Controllers
{
    public class AccountsController : Controller
    {
        private readonly ApplicationDbContext _context;
  
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AccountsController(ApplicationDbContext context,UserManager<ApplicationUser> userManager,RoleManager<IdentityRole> roleManager)
        {
            _context = context;
           
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
             
            return View(await _context.ApplicationUsers.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string? Id)
        {
            if (Id == null)
            {
                return View("Error");
            }
            ApplicationUser? applicationUser =await  _context.ApplicationUsers.FindAsync(Id);
            if (applicationUser == null)
            {
                return View("Error");
            }
            EditUserRole editUserRole = new() { User=applicationUser ,Roles=new()};

            var roles = _roleManager.Roles.ToList();
            foreach (var role in roles) {

                editUserRole.Roles.Add(new()
                {
                    Id = role.Id,
                    Name = role.Name,
                    IsSelected =await _userManager.IsInRoleAsync(applicationUser, role.Name)
                }); ;
            }


            return View(editUserRole);
        }
        [HttpPost]
        public async Task<IActionResult> EditRole(string? Id, EditUserRole editUserRole)
        {
            if (Id !=editUserRole.User.Id)
            {
                return View("Error");
            }
            foreach(var role in _roleManager.Roles)
            {
                await _userManager.RemoveFromRoleAsync(editUserRole.User, role.Name);
                 _context.SaveChanges();
            }
         
                await _userManager.AddToRolesAsync(editUserRole.User, editUserRole.Roles.Where(i=>i.IsSelected).Select(i=>i.Name));
                await _context.SaveChangesAsync();

            

            return RedirectToAction("Index");
        }
        }
}

SiliconApp/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SiliconApp.Attributes;
using SiliconApp.Data;
using SiliconApp.Models;

namespace SiliconApp.Controllers
{
    [BreadcrumbActionFilter]
    public class ContactsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Contacts.Include(c => c.Service);
            return View(await applicationDbContext.ToListAsync());
        }
 

        // GET: Contacts/Create
        public IActionResult Create()
        {
            ViewData["ServiceId"] = new SelectList(_context.Services, "Id", "Name");
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,ServiceId,Email,Message")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ServiceId"] = new SelectList(_context.Services, "Id", "Name", contact.ServiceId);
            return View(contact);
        }

 

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }

            var contact = await _context.Contacts
                .Include(c => c.Service)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return View("Error");
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.Contacts.FindAsync(id);
            if (contact != null)
            {
                _context.Contacts.Remove(contact);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
            return _context.Contacts.Any(e => e.Id == id);
        }
    }
}

SiliconApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Packaging;
using NuGet.Packaging.Licenses;
using SiliconApp.Attributes;
using SiliconApp.Data;
using SiliconApp.Models;
using SiliconApp.Models.VM;

namespace SiliconApp.Controllers
{
    [BreadcrumbActionFilter]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
     
 

        public CoursesController(ApplicationDbContext context,IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
    
        
        }

        // GET: Courses
        public async Task<IActionResult> Index(int CourseCategory,string? SearchCourse)
        {
           IEnumerable<Course> courses=await GetCourses();
        
            return View( await GetData(courses,CourseCategory, SearchCourse));
        }

        private  async Task<IEnumerable<Course>> GetCourses()
        {
            IEnumerable<Course> Courses=[];
         
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7136/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //GET Method
                HttpResponseMessage response = await client.GetAsync("api/Courses");
                if (response.IsSuccessStatusCode)
                {
                    Courses = await response.Content.ReadAsAsync<IEnumerable<Course>>();
                    return Courses;
                }
            
            }
            return Courses;
        }

        [HttpGet]
        public async Task<IActionResult> _indexCourseUser(int CourseCategory, string? SearchCourse)
        {
            IEnumerable<Course> courses = await GetCourses();
            return PartialView( await GetData(courses,CourseCategory, SearchCourse));
        }
        [HttpGet]
        public async Task<IActionResult> GetSavedCourseUser()
        {
            IEnumerable<Course> courses = await GetCourses();
            IEnumerable<Course>? CourseList =  await GetData(courses,0, null);
            if(CourseList != null)
            {
                CourseList= CourseList.Where(i=>i.IsSaved).ToList();
            }
            return PartialView(CourseList);
        }     
        [HttpGet]
        public async Task<IActionResult> DeleteAllSavedItem()
        {
            IEnumerable<Course> courses = await GetCourses();
            IEnumerable<Course>? CourseList = await  GetData(courses,0, null);
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
            if (CourseList != null)
            {
                CourseList= CourseList.Where(i=>i.IsSaved).ToList();
            }
            if (CourseList!=null)
            {
                foreach (var item in CourseList)
                {
                    List<UserSavedItem>? userSavedItem = _context.UserSavedItems.Where(i => i.CourseId == item.CourseId && i.ApplicationUserId == userId).ToList();
                    if (userSavedItem != null)
                    {
                        foreach(var item2 in userSavedItem)
                        {
                            _context.UserSavedItems.Remove(item2);
                            await _context.SaveChangesAsync();
                        }
                    }
                    
                
                }
            }
              CourseList = await  GetData(courses,0, null);
           
            if (CourseList != null)
            {
                CourseList = CourseList.Where(i => i.IsSaved).ToList();
            }
            return PartialView("GetSavedCourseUser",CourseList);
        }
        [HttpGet]
        public async Task<IActionResult> RemoveSaveCourse(int id)
        {
            IEnumerable<Course> courses = await GetCourses();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "";
          
           
                UserSavedItem? userSavedItem = _context.UserSavedItems.Where(i => i.CourseId == id && i.ApplicationUserId == userId).FirstOrDefault();
            if (userSavedItem != null)
            {
                _context.UserSavedItems.Remove(userSavedItem);
                await _context.SaveChangesAsync();
                
            }

            IEnumerable<Course>? CourseList = await  GetData(courses,0, null);
            if (CourseList != null)
            {
                CourseList = CourseList.Where(i => i.IsSaved).ToList();
            }

            return PartialView("GetSavedCourseUser", CourseList);
        }
        private async Task<IEnumerable<Course>?>  GetData(IEnumerable<Course> Courses, int CourseCategory, string? SearchCourse)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier)??"";
           

            foreach(Course item in Courses)
            {
                item.IsSaved = _context.UserSavedItems.Any(i => i.CourseId == item.CourseId && i.ApplicationUserId == userId && i.Is_Saved);
                item.IsLiked = _context.UserSavedItems.Any(i => i.CourseId == item.CourseId && i.ApplicationUserId == userId && i.Is_Liked);
            }

            if (CourseCategory > 0)
                Courses = Courses.Where(i => i.CategoryId == CourseCategory).ToList();

            if (!string.IsNullOrEmpty(SearchCourse))
            {
                Courses = Courses
                   .Where(i => i.CourseName.Contains(SearchCourse))
                   .ToList();
                ViewData["SearchCourse"] = SearchCourse;
            }


            ViewData["categories"] = new SelectList(_context.Catogoris, "CategoryId", "CategoryName", CourseCategory);
            return  Courses;
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Course course = new();
            if (id == null)
            {
                return PartialView(NotFound());
            }

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7136/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                //GET Method
                HttpResponseMessage response = await client.GetAsync($"api/Courses/{id}");
                if (response.IsSuccessStatusCode)
                {
                    course = await response.Content.ReadAsAsync<Course>();
                    return View(course);
                }

            }

           
                return PartialView(NotFound());
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Catogoris, "CategoryId", "CategoryName");
 
            Course course = new() { CourseLearns = [], CourseDetails = [], TeacherCourses = [], selectListItems = [] };
            course.CourseLearns.Add(new() { Id = 1 });
            course.CourseDetails.Add(new() { Id = 1 });
            course.TeacherCourses.Add(new() { Id = 1 });
            course.selectListItems.Add(new SelectList(_context.Teachers, "Id", "TeacherName"));

            return View(course);
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course course)
        {
            if (ModelState.IsValid)
            {
                string fileName = "";
                if (course.ImageFile != null)
                {
                    fileName = "/courses/images/" + course.ImageFile.FileName;
                    if (!Directory.Exists(_webHostEnvironment.WebRootPath + "/courses/images"))
                    {
                        Directory.CreateDirectory(_webHostEnvironment.WebRootPath + "/courses/images/");
                    }



                    using FileStream filestream = System.IO.File.Create(_webHostEnvironment.WebRootPath + fileName);
                    course.ImageFile.CopyTo(filestream);
                    filestream.Flush();
                    course.ImagePath = fileName;
                }

                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Catogoris, "CategoryId", "CategoryName", course.CategoryId);


            List<int> TeachersId = course.TeacherCourses.Select(i => i.CourseId).ToList();

            if (TeachersId.Any())
            {
                foreach (var i in TeachersId)
                {
                    course.selectListItems.Add(new SelectList(_context.Teachers, "Id", "TeacherName", i));
                }
            }
            else
            {
                course.selectListItems.Add(new SelectList(_context.Teachers, "Id", "TeacherName"));

            }

            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("Error");
            }

            var course = await _context.Courses

SiliconApp/Views/Shared/_Breadcrumbs.cshtml
@model List<Breadcrumb>
@if (Model != null)
{
    <nav aria-label="breadcrumb" style="background-color:transparent; color:white;padding:40px 0 0 50px">
        <ol class="breadcrumb  justify-content-center justify-content-md-start justify-content-lg-start justify-content-xl-start" style="background-color:transparent;">
            @foreach (var breadcrumb in Model)
            {
                if (breadcrumb.Text == "Home")
                {
                 
                    if (breadcrumb.Active)
                    {
                        <li class="breadcrumb-item active">   <a asp-action="@breadcrumb.Action" asp-controller="@breadcrumb.Controller"><i class="fa-solid fa-house" style="margin-right:5px;"></i>@breadcrumb.Text</a> </li>
                    }
                    else
                    {
                        <li class="breadcrumb-item" aria-current="page">   <i class="fa-solid fa-house"></i>@breadcrumb.Text</li>
                    }
                }
                else
                {
                    if (breadcrumb.Active)
                    {
                        <li class="breadcrumb-item active"><a asp-action="@breadcrumb.Action" asp-controller="@breadcrumb.Controller">@breadcrumb.Text</a> </li>
                    }
                    else
                    {
                        <li class="breadcrumb-item" aria-current="page">@breadcrumb.Text</li>
                    }
                }
             
            }
        </ol>
    </nav>
}

SiliconApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManager


<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiliconApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
  
    <link rel="stylesheet" href="~/SiliconApp.styles.css" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/dist/sweetalert2.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/loader.css" rel="stylesheet" />
</head>
<body class="">
    <header id="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm    box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SiliconApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Overviwe</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Feachers" asp-action="Index">Fachers</a>
                            </li>
                          
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Contacts" asp-action="Index">Contact</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Contacts" asp-action="Create">Contact</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || 1==1)
                        {
                            <li class="nav-item">
                                <a class="nav-link "   asp-controller="Accounts" asp-action="Index">Manage Users Roles</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="min-height:90vh">
        
        <main role="main" class="">
            <svg class="pl" id="pl" width="240" height="240" viewBox="0 0 240 240">
                <circle class="pl__ring pl__ring--a" cx="120" cy="120" r="105" fill="none" stroke="#000" stroke-width="20" stroke-dasharray="0 660" stroke-dashoffset="-330" stroke-linecap="round"></circle>
                <circle class="pl__ring pl__ring--b" cx="120" cy="120" r="35" fill="none" stroke="#000" stroke-width="20" stroke-dasharray="0 220" stroke-dashoffset="-110" stroke-linecap="round"></circle>
                <circle class="pl__ring pl__ring--c" cx="85" cy="120" r="70" fill="none" stroke="#000" stroke-width="20" stroke-dasharray="0 440" stroke-linecap="round"></circle>
                <circle class="pl__ring pl__ring--d" cx="155" cy="120" r="70" fill="none" stroke="#000" stroke-width="20" stroke-dasharray="0 440" stroke-linecap="round"></circle>
            </svg>
       
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted mt-4" style="overflow:hidden" >
        <div class="mt-1">
            <div class="row  d-flex justify-content-center  ">
                <div class=" col-3  d-flex justify-content-between  mt-3 ">
                    <button type="button" class="btn  btn-icon-footer">
                        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0,0,256,256">
                            <g fill="#32344d" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g transform="scale(5.12,5.12)"><path d="M41,4h-32c-2.76,0 -5,2.24 -5,5v32c0,2.76 2.24,5 5,5h32c2.76,0 5,-2.24 5,-5v-32c0,-2.76 -2.24,-5 -5,-5zM37,19h-2c-2.14,0 -3,0.5 -3,2v3h5l-1,5h-4v15h-5v-15h-4v-5h4v-3c0,-4 2,-7 6,-7c2.9,0 4,1 4,1z"></path></g></g>
                        </svg>
                    </button>
                    <button type="button" class="btn  btn-icon-footer">
                        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0,0,256,256">
                            <g fill="#32344d" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g transform="scale(8.53333,8.53333)"><path d="M28,6.937c-0.957,0.425 -1.985,0.711 -3.064,0.84c1.102,-0.66 1.947,-1.705 2.345,-2.951c-1.03,0.611 -2.172,1.055 -3.388,1.295c-0.973,-1.037 -2.359,-1.685 -3.893,-1.685c-2.946,0 -5.334,2.389 -5.334,5.334c0,0.418 0.048,0.826 0.138,1.215c-4.433,-0.222 -8.363,-2.346 -10.995,-5.574c-0.458,0.788 -0.721,1.704 -0.721,2.683c0,1.85 0.941,3.483 2.372,4.439c-0.874,-0.028 -1.697,-0.268 -2.416,-0.667c0,0.023 0,0.044 0,0.067c0,2.585 1.838,4.741 4.279,5.23c-0.447,0.122 -0.919,0.187 -1.406,0.187c-0.343,0 -0.678,-0.034 -1.003,-0.095c0.679,2.119 2.649,3.662 4.983,3.705c-1.825,1.431 -4.125,2.284 -6.625,2.284c-0.43,0 -0.855,-0.025 -1.273,-0.075c2.361,1.513 5.164,2.396 8.177,2.396c9.812,0 15.176,-8.128 15.176,-15.177c0,-0.231 -0.005,-0.461 -0.015,-0.69c1.043,-0.753 1.948,-1.692 2.663,-2.761z"></path></g></g>
                        </svg>
                    </button>
                    <button type="button" class="btn  btn-icon-footer">
                        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0,0,256,256">
                            <g fill="#32344d" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g transform="scale(5.12,5.12)"><path d="M16,3c-7.17,0 -13,5.83 -13,13v18c0,7.17 5.83,13 13,13h18c7.17,0 13,-5.83 13,-13v-18c0,-7.17 -5.83,-13 -13,-13zM37,11c1.1,0 2,0.9 2,2c0,1.1 -0.9,2 -2,2c-1.1,0 -2,-0.9 -2,-2c0,-1.1 0.9,-2 2,-2zM25,14c6.07,0 11,4.93 11,11c0,6.07 -4.93,11 -11,11c-6.07,0 -11,-4.93 -11,-11c0,-6.07 4.93,-11 11,-11zM25,16c-4.96,0 -9,4.04 -9,9c0,4.96 4.04,9 9,9c4.96,0 9,-4.04 9,-9c0,-4.96 -4.04,-9 -9,-9z"></path></g></g>
                        </svg>
                    </button>
                    <button type="button" class="btn  btn-icon-footer">
                        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0,0,256,256">
                            <g fill="#32344d" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g transform="scale(5.12,5.12)"><path d="M44.89844,14.5c-0.39844,-2.19922 -2.29687,-3.80078 -4.5,-4.30078c-3.29687,-0.69922 -9.39844,-1.19922 -16,-1.19922c-6.59766,0 -12.79687,0.5 -16.09766,1.19922c-2.19922,0.5 -4.10156,2 -4.5,4.30078c-0.40234,2.5 -0.80078,6 -0.80078,10.5c0,4.5 0.39844,8 0.89844,10.5c0.40234,2.19922 2.30078,3.80078 4.5,4.30078c3.5,0.69922 9.5,1.19922 16.10156,1.19922c6.60156,0 12.60156,-0.5 16.10156,-1.19922c2.19922,-0.5 4.09766,-2 4.5,-4.30078c0.39844,-2.5 0.89844,-6.10156 1,-10.5c-0.20312,-4.5 -0.70312,-8 -1.20312,-10.5zM19,32v-14l12.19922,7z"></path></g></g>
                        </svg>
                    </button>

                </div>
            </div>
            <div class="row  d-flex justify-content-center  mt-3 ">
                <div class=" col-8 d-flex justify-content-center">
                    <div class="para-fotter">
                        <p> © 2024 Silicon. All rights reserved. Pulvinar urna condimentum amet tempor, ornare integer. Lorem odio justo malesuada <br>
                                           viverra aliquet quisque turpis non. Feugiat in odio non nunc ornare consectetur.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/unobtrusiveajax.js"></script>
    <script src="~/lib/sweetalert2/dist/sweetalert2.all.js"></script>
    <script src="~/lib/sweetalert2/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/darklight.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome/js/all.js"></script>
    <script src="~/js/mastertable.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>